# Generated by Django 4.1.3 on 2022-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_admin',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
            ],
        ),
    ]
