# Generated by Django 4.1.3 on 2022-11-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form_admin',
            new_name='admin_model',
        ),
    ]
