# Generated by Django 4.1.3 on 2022-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_form_admin_admin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
            ],
        ),
    ]
