# Generated by Django 4.1.3 on 2022-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_function_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='function_model',
            name='func_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
