# Generated by Django 4.1.3 on 2022-11-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_venue_model_booking_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function_model',
            name='guest_house_pesons',
        ),
    ]
