# Generated by Django 4.1.3 on 2022-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_function_model_guest_house_pesons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='dept_name',
            field=models.CharField(max_length=100),
        ),
    ]
