# Generated by Django 4.1.3 on 2022-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_function_model_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='func_students_year_course',
            field=models.CharField(max_length=30),
        ),
    ]
