# Generated by Django 4.1.3 on 2022-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_function_model_func_students_year_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='organizer_mail_id',
            field=models.EmailField(max_length=100),
        ),
    ]
