# Generated by Django 4.1.3 on 2022-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_function_model_organizer_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='organizer_mail_id',
            field=models.EmailField(max_length=150),
        ),
    ]
