# Generated by Django 4.1.3 on 2022-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_function_model_document_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='guest_house_from_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='guest_house_to_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='transport_req_date',
            field=models.CharField(max_length=30),
        ),
    ]
