# Generated by Django 4.1.3 on 2022-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_function_model_guest_house_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='lunch_required_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='refreshment_for_guest_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='refreshment_for_student_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='transport_drop_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='transport_pickup_time',
            field=models.CharField(max_length=30),
        ),
    ]
