# Generated by Django 4.1.3 on 2023-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_function_model_lunch_required_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function_model',
            name='document_pdf',
        ),
        migrations.AddField(
            model_name='booking_model',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='function_model',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='function_model',
            name='time_stamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
