# Generated by Django 4.1.3 on 2023-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_function_model_document_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='document_pdf',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
