# Generated by Django 4.1.3 on 2023-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_function_model_document_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='payment_through',
            field=models.CharField(max_length=35),
        ),
    ]
