# Generated by Django 4.1.3 on 2023-01-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_function_model_payment_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_model',
            name='admin_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='staff_id',
            field=models.CharField(max_length=25),
        ),
    ]
