# Generated by Django 4.1.3 on 2023-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_admin_model_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
