# Generated by Django 4.1.3 on 2023-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_booking_model_days_booking_model_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='photographer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
