# Generated by Django 4.1.3 on 2023-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_function_model_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='session',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
