# Generated by Django 4.1.3 on 2023-02-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_booking_model_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_model',
            old_name='days',
            new_name='func_days',
        ),
        migrations.AlterUniqueTogether(
            name='booking_model',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='booking_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking_model',
            unique_together={('venue', 'booking_date', 'booking_end_date', 'session')},
        ),
        migrations.RemoveField(
            model_name='booking_model',
            name='duration',
        ),
    ]
