# Generated by Django 4.1.3 on 2023-02-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_days_booking_model_func_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='month',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
