# Generated by Django 4.1.3 on 2023-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_booking_model_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='func_students_external',
            field=models.IntegerField(null=True),
        ),
    ]
