# Generated by Django 4.1.3 on 2023-02-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_booking_model_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking_model',
            unique_together={('venue', 'booking_date', 'booking_end_date', 'session', 'month')},
        ),
    ]
