# Generated by Django 4.1.3 on 2023-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_venue_model_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='func_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='function_model',
            name='hod_status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='function_model',
            name='principal_status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking_model',
            unique_together={('venue', 'booking_date', 'booking_end_date', 'month')},
        ),
        migrations.RemoveField(
            model_name='booking_model',
            name='session',
        ),
    ]
